export const GET_EMPLOYERS = 'GET_EMPLOYERS';
export const DELETE_EMPLOYERS = 'DELETE_EMPLOYERS';
export const ADD_EMPLOYERS = 'ADD_EMPLOYERS';
export const GET_SINGLE_EMPLOYER = 'GET_SINGLE_EMPLOYER';
export const UPDATE_EMPLOYERS = 'UPDATE_EMPLOYERS';